//定数
#define SEVEN_SEG_CLK_PIN PIN_PC0
#define SEVEN_SEG_DIO_PIN PIN_PC1

#define ONE_PPS_PIN PIN_PC2
#define GPS_OFF_PIN PIN_PC3

#define SD_DI_PIN PIN_PA4
#define SD_DO_PIN PIN_PA5
#define SD_SCLK_PIN PIN_PA6
#define SD_CS_PIN PIN_PA7

#define CDS_PIN PIN_PD6

#define COL_LED_PIN1 PIN_PD1
#define COL_LED_PIN2 PIN_PD2
